import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  modal: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.8)",
  },
  modalContainer: {
    backgroundColor: "#1E1E20",
    borderRadius: 20,
    padding: 25,
    alignItems: "center",
    shadowColor: "#FFD700",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
    width: 350,
    maxHeight: 500,
    borderWidth: 2,
    borderColor: "#FFD700",
    position: "relative",
  },
  title: {
    color: "#FFD700",
    fontSize: 32,
    fontWeight: "bold",
    textAlign: "center",
    textShadowColor: "#000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
  },
  score: {
    color: "#02F702",
    fontSize: 36,
    fontWeight: "bold",
    marginTop: 20,
    textAlign: "center",
    textShadowColor: "#000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
  },
  spacecoins: {
    color: "#02F702",
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 25,
    textAlign: "center",
    textShadowColor: "#000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
  },
  button: {
    width: "90%",
    backgroundColor: "#FF4500",
    borderRadius: 15,
    paddingVertical: 14,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 10,
    borderWidth: 2,
    borderColor: "#FFD700",
  },
  buttonText: {
    fontSize: 18,
    color: "#FFF",
    textAlign: "center",
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  closeButton: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "#FF4500",
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#FFD700",
  },
  closeButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  input: {
    height: 50,
    width: "85%",
    marginTop: 20,
    marginBottom: 20,
    borderWidth: 2,
    borderRadius: 15,
    paddingHorizontal: 15,
    fontSize: 18,
    backgroundColor: "#FFF",
    color: "#0000000",
    borderColor: "#FFD700",
    textAlign: "center",
    textShadowColor: "",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
});
