import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  colors: {
    primary: "aqua",
    background: "rgba(0, 0, 0, 0.7)",
    button: "rgba(0, 128, 128, 0.8)",
    buttonText: "#fff",
    inputBackground: "#fff",
    inputText: "#000",
  },

  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  video: {
    ...StyleSheet.absoluteFillObject,
    zIndex: -1,
  },

  backgroundImage: {
    position: "absolute",
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  header: {
    marginTop: 170,
    alignItems: "center",
  },
  title: {
    color: "aqua",
    fontSize: 32,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 10,
    textShadowColor: "rgba(0, 0, 0, 0.6)",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
  },
  subTitle: {
    color: "aqua",
    fontSize: 18,
    marginTop: 5,
    textAlign: "center",
    textShadowColor: "rgba(0, 0, 0, 0.6)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  shipButton: {
    marginTop: 20,
    height: 120,
    width: 120,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 128, 128, 0.8)",
    borderRadius: 60,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
  },
  shipImage: {
    width: 1050,
    height: 180,
    resizeMode: "contain",
  },
  settings: {
    width: "90%",
    position: "absolute",
    bottom: 55,
    alignItems: "center",
    paddingVertical: 20,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 8,
  },
  settingsTitle: {
    color: "aqua",
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 20,
  },
  settingButton: {
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 8,
    marginVertical: 8,
    width: "60%",
    alignItems: "center",
    backgroundColor: "rgba(0, 128, 128, 0.8)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  settingText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  volumeControl: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 3,
    paddingRight: 5,
    marginRight: 36,
    width: "50%",
    marginBottom: 2,
    gap: 6,
  },
  input: {
    color: "#fff",
    textAlign:"center",
    fontWeight:"bold",
    padding: 12,
    borderRadius: 8,
    marginTop: 12,
    width: "60%",
    fontSize: 16,
    borderWidth: 1,
    borderColor: "rgba(0, 0, 0, 0.2)",
    backgroundColor: "rgba(0, 128, 128, 0.8)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  saveButton: {
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
    alignItems: "center",
    width: "60%",
    backgroundColor: "rgba(0, 128, 128, 0.8)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  saveButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
});
