import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  video: {
    ...StyleSheet.absoluteFillObject,
    zIndex: -1,
  },
  settings: {
    height: 700,
    width: 320,
    position: "absolute",
    alignItems: "center",
    paddingVertical: 15,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 10,
    top: 8, // Ajusta posição vertical
  },
  settingsTitle: {
    color: "#fff",
    fontSize: 40,
    fontWeight: "bold",
    marginBottom: 20,
    textShadowColor: "rgba(0, 0, 0, 0.7)",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 6,
  },
  section: {
    marginBottom: 20,
    width: 350,
    alignItems: "center",
    paddingTop: 10, // Espaçamento acima do conteúdo
    borderTopWidth: 1, // Borda na parte superior
    borderTopColor: "rgba(255, 255, 255, 0.4)", // Cor da borda superior
    paddingBottom: 10,
  },
  sectionTitle: {
    color: "#FFD700",
    fontSize: 26,
    fontWeight: "bold",
    marginBottom: 10,
    textShadowColor: "rgba(0, 0, 0, 0.8)",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 6,
    textTransform: "uppercase",
  },
  settingOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: 300,
    marginVertical: 12,
    paddingHorizontal: 10,
  },
  settingButton: {
    position: "relative",
    left: 33,
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 12,
    width: 210,
    alignItems: "center",
    backgroundColor: "rgba(0, 128, 128, 0.8)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 5,
    elevation: 6,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  creditosButton: {
    marginTop: 8,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    width: 200,
    alignItems: "center",
    backgroundColor: "rgba(0, 128, 128, 0.8)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 5,
    elevation: 6,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  creditosTitle: {
    color: "aqua",
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 10,
    textShadowColor: "rgba(0, 0, 0, 0.6)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 4,
    textTransform: "uppercase",
  },
  largeIcon: {
    position: "relative",
    left: 15,
    width: 50,
    height: 50,
  },
  settingText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    textShadowColor: "rgba(0, 0, 0, 0.6)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 4,
  },
  
  input: {
    color: "#000000",
    textAlign: "center",
    fontWeight: "bold",
    padding: 12,
    borderRadius: 8,
    marginTop: 12,
    width:150,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  saveButton: {
    padding: 12,
    borderRadius: 12,
    marginTop: 20,
    alignItems: "center",
    width: 210,
    backgroundColor: "rgba(0, 128, 128, 0.8)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 5,
    elevation: 6,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  saveButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    textShadowColor: "rgba(0, 0, 0, 0.5)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
});
